export const constatentKey = {
  AUTH_SIGNIN: 'AUTH_SIGNIN',

  // user
  GET_USER_MANAGE_KEY: 'GET_USER_MANAGE_KEY',
  GET_ONCE_USER_MANAGE_KEY: 'GET_ONCE_USER_MANAGE_KEY',
  POST_GET_USER_MANAGE_KEY: 'POST_GET_USER_MANAGE_KEY',
  PUT_USER_MANAGE_KEY: 'PUT_USER_MANAGE_KEY',
  DELETE_GET_USER_MANAGE_KEY: 'DELETE_GET_USER_MANAGE_KEY',

  // house
  GET_HOUSE_MANAGE_KEY: 'GET_HOUSE_MANAGE_KEY',
  GET_ONCE_HOUSE_MANAGE_KEY: 'GET_ONCE_HOUSE_MANAGE_KEY',
  POST_GET_HOUSE_MANAGE_KEY: 'POST_GET_HOUSE_MANAGE_KEY',
  PUT_HOUSE_MANAGE_KEY: 'PUT_HOUSE_MANAGE_KEY',
  DELETE_GET_HOUSE_MANAGE_KEY: 'DELETE_GET_HOUSE_MANAGE_KEY',

  // role
  ROLE_MANAGE_KEY: 'ROLE_MANAGE_KEY',
  GET_ONCE_ROLE_MANAGE_KEY: 'GET_ONCE_ROLE_MANAGE_KEY',
  POST_ROLE_MANAGE_KEY: 'POST_ROLE_MANAGE_KEY',
  DELETE_ROLE_MANAGE_KEY: 'DELETE_ROLE_MANAGE_KEY',

  // categorires
  GET_CATEGORIES_MANAGE_KEY: 'GET_CATEGORIES_MANAGE_KEY',
  GET_ONCECATEGORIES_MANAGE_KEY: 'GET_ONCECATEGORIES_MANAGE_KEY',
  DELETE_CATEGORIES_MANAGE_KEY: 'DELETE_CATEGORIES_MANAGE_KEY',
  POST_CATEGORIES_MANAGE_KEY: 'POST_CATEGORIES_MANAGE_KEY',
  PUT_CATEGORIES_MANAGE_KEY: 'PUT_CATEGORIES_MANAGE_KEY',

  // realty
  GET_REALTY_MANAGE_KEY: 'GET_REALTY_MANAGE_KEY',
  POST_REALTY_MANAGE_KEY: 'POST_REALTY_MANAGE_KEY',
  PUT_REALTY_MANAGE_KEY: 'PUT_REALTY_MANAGE_KEY',
  DELETE_REALTY_MANAGE_KEY: 'DELETE_REALTY_MANAGE_KEY',
} as const;
