export { default as HeroDeleteIcon } from './DeleteIcon'
export { default as HeroEyeIcon } from './EyeIcon'
export { default as HeroHomeIcon } from './HomeIcon'
export { default as HeroManageSpectHouse } from './ManageSpectHouse'
export { default as HeroManageUserIcon } from './ManageUserIcon'
export { default as HeroPencilIcon } from './PencilIcon'
export { default as HeroUserRoleIcon } from './UserRoleIcon'