import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "@/styles/globals.scss";

const kanitFont = Kanit({
  subsets: ["latin", 'thai'],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "HIEinspect dashboard",
  description: "Generated by create next app",
  applicationName: 'HIEinspect of us'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kanitFont.className}>{children}</body>
    </html>
  );
}
