import { Suspense } from 'react';
import type { Metadata } from 'next';
import { Kanit } from 'next/font/google';
import AuthGuestGuard from '@/contexts/AuthGuestGuard';
import TanstackProvider from '@/contexts/TanstackProvider';
import Providers from '@/contexts/ToastProvider';
import Loading from '@/components/nextui/Loading/Loading';
import '@/styles/globals.scss';

const kanitFont = Kanit({
  subsets: ['latin', 'thai'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'HIEinspect dashboard',
  description: 'Generated by create next app',
  applicationName: 'HIEinspect of us',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kanitFont.className}>
        <Providers>
          <TanstackProvider>
            <Suspense fallback={<Loading />}>
              <AuthGuestGuard>{children}</AuthGuestGuard>
            </Suspense>
          </TanstackProvider>
        </Providers>
      </body>
    </html>
  );
}
