import type { Metadata } from 'next';
import { Kanit } from 'next/font/google';
import AuthGuestGuard from '@/contexts/AuthGuestGuard';
import TanstackProvider from '@/contexts/TanstackProvider';
import Providers from '@/contexts/ToastProvider';
import '@/styles/globals.scss';

const kanitFont = Kanit({
  subsets: ['latin', 'thai'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'HIEinspect dashboard',
  description: 'Generated by create next app',
  applicationName: 'HIEinspect of us',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kanitFont.className}>
        <TanstackProvider>
          <AuthGuestGuard>
            <Providers>{children}</Providers>
          </AuthGuestGuard>
        </TanstackProvider>
      </body>
    </html>
  );
}
